# Generated by Django 5.2.7 on 2025-10-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical/Electronics Engineering'), ('mechanical', 'Mechanical Engineering'), ('computer', 'Computer Engineering'), ('general', 'General Engineering')], max_length=50)),
                ('question', models.TextField(help_text='The question students might ask')),
                ('answer', models.TextField(help_text='The answer to provide')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for better matching', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Engineering Q&A',
                'verbose_name_plural': 'Engineering Q&As',
                'ordering': ['-created_at'],
            },
        ),
    ]
