# Generated by Django 5.2.7 on 2025-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringqa',
            name='category',
            field=models.CharField(choices=[('abet', 'Agricultural and Bio-Enviromental Engineering Technology'), ('cet', 'Civil Engineering Technology'), ('cte', 'Computer Engineering Technology'), ('eeet', 'Electrical/Electronics Engineering Technology'), ('met', 'Mechanical Engineering Technology')], max_length=50),
        ),
    ]
