# Generated by Django 5.2.7 on 2025-12-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_expand_knowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringQA',
            fields=[
            ],
            options={
                'verbose_name': 'Engineering Q&A',
                'verbose_name_plural': 'Engineering Q&As',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge.rugipoknowledge',),
        ),
        migrations.AlterModelOptions(
            name='rugipoknowledge',
            options={'ordering': ['-created_at'], 'verbose_name': 'RUGIPO Knowledge', 'verbose_name_plural': 'RUGIPO Knowledge Base'},
        ),
        migrations.AlterModelOptions(
            name='scraperurl',
            options={'ordering': ['url'], 'verbose_name': 'Scraper URL', 'verbose_name_plural': 'Scraper URLs'},
        ),
        migrations.AlterField(
            model_name='rugipoknowledge',
            name='category',
            field=models.CharField(choices=[('general', 'General RUGIPO Information'), ('abet', 'Agricultural and Bio-Environmental Engineering Technology'), ('cet', 'Civil Engineering Technology'), ('cte', 'Computer Engineering Technology'), ('eeet', 'Electrical/Electronics Engineering Technology'), ('met', 'Mechanical Engineering Technology'), ('admissions', 'Admissions & Registration'), ('facilities', 'Facilities & Campus'), ('news', 'News & Events'), ('academic', 'Academic Programs'), ('student_services', 'Student Services')], max_length=50),
        ),
    ]
