# Generated by Django 5.1.6 on 2025-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_engineeringqa_alter_rugipoknowledge_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rugipoknowledge',
            name='knowledge_type',
            field=models.CharField(choices=[('engineering', 'Engineering Knowledge'), ('general', 'General Knowledge')], default='general', help_text='Type of knowledge: Engineering or General', max_length=20),
        ),
        migrations.AlterField(
            model_name='rugipoknowledge',
            name='category',
            field=models.CharField(choices=[('general', 'General RUGIPO Information'), ('abet', 'Agricultural and Bio-Environmental Engineering Technology'), ('cet', 'Civil Engineering Technology'), ('cte', 'Computer Engineering Technology'), ('eeet', 'Electrical/Electronics Engineering Technology'), ('met', 'Mechanical Engineering Technology'), ('admissions', 'Admissions & Registration'), ('facilities', 'Facilities & Campus'), ('news', 'News & Events'), ('academic', 'Academic Programs'), ('student_services', 'Student Services'), ('fees', 'Fees & Payments')], max_length=50),
        ),
    ]
